# -*- coding: utf-8 -*-
"""Seminar analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MoEqr-Z1KKdpIQrcKQYWl4n5APHOx5lc
"""

from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import random
import statsmodels.api as sm

for dirname, _, filenames in os.walk('/data/input'):
    for filename in filenames:

        print(os.path.join(dirname, filename))

def plotPerColumnDistribution(df, nGraphShown, nGraphPerRow):
    nunique = df.nunique()
    df = df[[col for col in df if nunique[col] > 1 and nunique[col] < 50]] # For displaying purposes, pick columns that have between 1 and 50 unique values
    nRow, nCol = df.shape
    columnNames = list(df)
    nGraphRow = int((nCol + nGraphPerRow - 1) / nGraphPerRow)
    plt.figure(num = None, figsize = (6 * nGraphPerRow, 8 * nGraphRow), dpi = 80, facecolor = 'w', edgecolor = 'k')
    for i in range(min(nCol, nGraphShown)):
        plt.subplot(nGraphRow, nGraphPerRow, i + 1)
        columnDf = df.iloc[:, i]
        if (not np.issubdtype(type(columnDf.iloc[0]), np.number)):
            valueCounts = columnDf.value_counts()
            valueCounts.plot.bar()
        else:
            columnDf.hist()
        plt.ylabel('counts')
        plt.xticks(rotation = 90)
        plt.title(f'{columnNames[i]} (column {i})')
    plt.tight_layout(pad = 1.0, w_pad = 1.0, h_pad = 1.0)
    plt.show()

def plotCorrelationMatrix(df, graphWidth):
    filename = df.dataframeName
    df = df.dropna('columns') # drop columns with NaN
    df = df[[col for col in df if df[col].nunique() > 1]] # keep columns where there are more than 1 unique values
    if df.shape[1] < 2:
        print(f'No correlation plots shown: The number of non-NaN or constant columns ({df.shape[1]}) is less than 2')
        return
    corr = df.corr()
    plt.figure(num=None, figsize=(graphWidth, graphWidth), dpi=80, facecolor='w', edgecolor='k')
    corrMat = plt.matshow(corr, fignum = 1)
    plt.xticks(range(len(corr.columns)), corr.columns, rotation=90)
    plt.yticks(range(len(corr.columns)), corr.columns)
    plt.gca().xaxis.tick_bottom()
    plt.colorbar(corrMat)
    plt.title(f'Correlation Matrix for {filename}', fontsize=15)
    plt.show()

def plotScatterMatrix(df, plotSize, textSize):
    df = df.select_dtypes(include =[np.number]) # keep only numerical columns
    # Remove rows and columns that would lead to df being singular
    df = df.dropna('columns')
    df = df[[col for col in df if df[col].nunique() > 1]] # keep columns where there are more than 1 unique values
    columnNames = list(df)
    if len(columnNames) > 10: # reduce the number of columns for matrix inversion of kernel density plots
        columnNames = columnNames[:10]
    df = df[columnNames]
    ax = pd.plotting.scatter_matrix(df, alpha=0.75, figsize=[plotSize, plotSize], diagonal='kde')
    corrs = df.corr().values
    for i, j in zip(*plt.np.triu_indices_from(ax, k = 1)):
        ax[i, j].annotate('Corr. coef = %.3f' % corrs[i, j], (0.8, 0.2), xycoords='axes fraction', ha='center', va='center', size=textSize)
    plt.suptitle('Scatter and Density Plot')
    plt.show()

nRowsRead = 1000
df1 = pd.read_csv(r"df_test.csv", delimiter=',', nrows = nRowsRead)
df1.dataframeName = 'df_test.csv'
nRow, nCol = df1.shape
print(f'There are {nRow} rows and {nCol} columns')

df1.head(5)

plotPerColumnDistribution(df1,10,5)

plotCorrelationMatrix(df1, 24)

plotScatterMatrix(df1, 30, 15)

df1.columns

cols = [6,7,8,10,11,12]

features = df1[df1.columns[cols]]


type(features)

type_of_atom = df1[df1.columns[4]]
type_of_atom

dd_linear_model = sm.OLS(type_of_atom, features)
dd_result = dd_linear_model.fit()
dd_result.summary()

type(dd_linear_model.fit())

print(str(dd_result.summary()))

dd_result.rsquared
dd_result.conf_int(alpha = 0.05, cols = None)

dd_result.ess.sum() + dd_result.resid.sum()

plt.plot(df1.type, dd_result.resid)
plt.xlabel = "Actual Price",

now adding more columns

cols = [6,7,8,10,11,12,17,18,23,24,29,30]

features = df1[df1.columns[cols]]


type(features)

type_of_atom = df1[df1.columns[4]]
type_of_atom

dd_linear_model = sm.OLS(type_of_atom, features)
dd_result = dd_linear_model.fit()
dd_result.summary()

type(dd_linear_model.fit())

print(str(dd_result.summary()))

dd_result.rsquared
dd_result.conf_int(alpha = 0.05, cols = None)

dd_result.ess.sum() + dd_result.resid.sum()

plt.plot(df1.type, dd_result.resid)
plt.xlabel = "Actual Price",

